In [1]:
import numpy as np
import numpy.linalg as npl

1. Jacobi
Implementar una función que reciba una matriz $A$ y calcule la matriz de iteración de Jacobi $B_J$. Es importante no cometer la ingenuidad de aplicar np.diag($D$), donde $D$ es la matriz diagonal de $A$. La gracia del algoritmo es que invertir $D$ es fácil, de modo que no deberíamos usar un solver automático, que probablemente haga más cuentas de las necesarias. Hay dos caminos que se pueden tomar: 

a) pensar cómo se puede calcular $D^{-1}$ de manera sencilla, 

b) (mejor aún) pensar cómo se puede calcular $-D^{-1}(L+U)$ sin calcular explícitamente la matriz completa $D^{-1}$. 

In [4]:
def matrizJacobi(A):
    d = np.diag(A)
    D = np.diag(d)
    D_inv = np.diag(np.reciprocal(d))
    A_triu = np.triu(A)
    A_tril = np.tril(A)
    L = A_tril - D
    U = A_triu - D
    
    BJ = (-1) * D_inv @  (L + U) 
    return BJ

Implementar una función que aplique el método de Jacobi para resolver un sistema de la forma $Ax=b$. El programa debe recibir como datos: la matriz $A$, el vector $b$, un dato inicial $x_0$, un número máximo de iteraciones $N$ y una tolerancia $tol$. Debe computar la matriz de Jacobi haciendo uso de la función matrizJacobi y aplicar la iteración un cierto número de veces. Se debe detener si se cumple cualquiera de las siguientes condiciones: a) se alcanza el número máximo de iteraciones $N$ o b) la diferencia (en norma 2) entre dos aproximaciones sucesivas es menor que la tolerancia $tol$. En el caso de que el programa se detenga a causa de la primera condición se debe imprimir en pantalla un aviso de que se alcanzó el número máximo de iteraciones y que, por lo tanto, no está garantizada la convergencia. Probar el programa con alguno de los ejemplos de la práctica. 

In [13]:
def jacobi(A,b,x0,N=100,tol=1e-8):
    BJ = matrizJacobi(A) 
    d = np.diag(A)
    D = np.diag(d)
    D_inv = np.diag(np.reciprocal(d))
    autovalores = np.linalg.eigvals(BJ)
    rad_esp = np.max(np.abs(autovalores))
    x = np.zeros( (len(x0),N+1) ) ###np.zeros(len(x0),N)   
    x[:,0]= x0
    for i in range(N):
      x[:,i+1] = BJ @ x[:,i] + D_inv @ b
      if npl.norm((x[:,i+1] - x[:,i]), ord=2) < tol:
        print('Converge, y el número de iteraciones es', i+1)
        break
    else:
        print('Se alcanzó el maximo de iteraciones')
    print('El radio espectral es:', rad_esp)
    return x[:,i+1]



In [6]:
A = np.arange(1.,17.).reshape((4,4))
b = np.arange(2.,6.)
x0 = np.arange(5.,9.)
jacobi(A,b,x0, N=5, tol =.05)


Se alcanzó el maximo de iteraciones
El radio espectral es: 3.9361900689860168


array([-11863.91127181,  -5593.53168044,  -5022.58808123,  -4807.85923152])

2. Sabemos que un método iterativo converge si el radio espectral de la matriz de iteración es menor que $1$. Esto se puede chequear usando el comando np.linalg.eig o el comando np.linalg.eigvals que devuelven los autovalores de una matriz (el primero devuelve también los autovectores). Generar varias matrices $A$, construir la matriz de iteración de Jacobi para cada $A$ y verificar si el radio espectral resulta menor que $1$. Cuando esto se cumpla, resolver un sistema usando la función $jacobi$ y confirmar que converge. Chequear que la convergencia sea más rápida (requiera menos iteraciones) cuanto menor sea el radio espectral. 

In [7]:
#Ejemplo donde no converge
A_3 = np.matrix([[1., 2.], [5., 3.]])
J3 = matrizJacobi(A_3)
autovalores3 = np.linalg.eigvals(J3)
autovalores3

array([ 1.82574186, -1.82574186])

In [8]:
x0 = (1, 2)
b = (2, 1)
k = jacobi(A_3, b, x0, N=50, tol=1e-08)
k

Se alcanzó el maximo de iteraciones
El radio espectral es: 1.8257418583505538


array([1.85465561e+13, 8.43025277e+12])

In [14]:
#Ejemplo donde converge
A_2 = np.matrix([[2., 1.], [3., 6.]])
J2 = matrizJacobi(A_2)
autovalores2 = np.linalg.eigvals(J2)
autovalores2


array([ 0.5, -0.5])

In [15]:

x0 = (1, 2)
b = (2, 1)
l = jacobi(A_2, b, x0, N=50, tol=.004)
l

Converge, y el número de iteraciones es 11
El radio espectral es: 0.5000000000000001


array([ 1.22102865, -0.44433594])

In [11]:
#Ejemplo donde converge y el radio espectral es menor
A_4 = np.matrix([[2., 1.], [1., 6.]])
J4 = matrizJacobi(A_4)
autovalores4 = np.linalg.eigvals(J4)
autovalores4

array([ 0.28867513, -0.28867513])

In [12]:
x0 = (1, 2)
b = (2, 1)
r = jacobi(A_4, b, x0, N=50, tol=.004)
r

Converge, y el numero de iteraciones es 7
El radio espectral es: 0.28867513459481287


array([0.9994213, 0.       ])